# Metadata for this specific system configuration preset

config_version = 1

# Name of the system; used internally to reference it and for paths, etc.
name = "ats590"

# Full "pretty" name of the system, e.g. for UI text
name_full = "ATS590 Test System"
# Freeform description of the system's author
author = "C.A.M. Gerlach, Dr. Udaysankar Nair and the ATS 590 class"
# Freeform description of the system's intended function and purpose
description = "System configuration for the ATS590 Low Cost Environmental Sensing class"
# Website where visitors can learn more about the system or view the data
homepage = "https://www.uah.edu"
# Repository containing the system's source code
repo = "https://github.com/hamma-dev/mjolnir-ats590"
# SPDX license identifier for the this configuration package (MIT/Expat)
license = "MIT"

# Version of the config package; should follow SemVer and PEP 396
version = "0.2.0"
# Minimum Brokkr version this version of the config package needs to work
brokkr_version_min = "0.4.0dev0"
# As above, but maximum version (e.g. "0.3.99" for < 0.4.x)
brokkr_version_max = ""
# Ibid, for Sindri
sindri_version_min = "0.3.0"
sindri_version_max = ""
